const TUBES={blue:{name:"Light Blue",short:"Blue",css:"blue",additive:"Sodium citrate"},gold:{name:"Gold / Tiger SST",short:"Gold",css:"gold",additive:"Serum separator"},lavender:{name:"Lavender",short:"Lavender",css:"lavender",additive:"EDTA"},green:{name:"Green",short:"Green",css:"green",additive:"Heparin"},red:{name:"Red",short:"Red",css:"red",additive:"Serum"},gray:{name:"Gray",short:"Gray",css:"gray",additive:"Fluoride / oxalate"}};

const SCENARIOS=[
{id:"routine-primary-care",category:"Routine Primary Care",title:"Annual Preventive Labs",patient:{name:"Jordan Miller",dob:"04/18/1994",mrn:"TRAIN-001"},note:"I'm usually pretty easy to draw. Either arm is fine.",orders:[{test:"CBC with differential",tube:"lavender"},{test:"Comprehensive Metabolic Panel (CMP)",tube:"gold"},{test:"Hemoglobin A1c",tube:"lavender"},{test:"TSH with reflex to Free T4",tube:"gold"}],expectedOrder:["gold","lavender"],explanation:"For this training scenario, the serum tests are grouped with Gold/SST and the CBC/A1c with Lavender EDTA. Gold/SST is collected before Lavender EDTA."},
{id:"fasting-metabolic",category:"Pre-Collection Check",title:"Fasting Metabolic Labs",patient:{name:"Avery Chen",dob:"11/02/1987",mrn:"TRAIN-002"},note:"I haven't eaten since last night, but I did have black coffee this morning.",orders:[{test:"Lipid Panel",tube:"gold"},{test:"Comprehensive Metabolic Panel",tube:"gold"},{test:"Hemoglobin A1c",tube:"lavender"},{test:"CBC with differential",tube:"lavender"}],expectedOrder:["gold","lavender"],safety:{question:"The order says FASTING and the patient had black coffee. What is the best next step?",options:["Assume black coffee is always allowed and draw immediately.","Verify the fasting instructions for the ordered tests or ask the supervisor before collection.","Cancel all laboratory orders.","Tell the patient to drink juice first."],correctIndex:1,explanation:"Do not guess about preparation requirements. Verify the current lab/provider instructions before collection."},explanation:"The key skill here is both correct tube selection and knowing when a preparation instruction needs verification."},
{id:"hormone-monitoring",category:"Hormone Monitoring",title:"Routine Follow-Up",patient:{name:"Rowan Parker",dob:"07/26/2001",mrn:"TRAIN-003"},note:"My veins roll sometimes, and people usually have better luck with a butterfly.",orders:[{test:"Estradiol",tube:"gold"},{test:"Total Testosterone",tube:"gold"},{test:"CBC",tube:"lavender"},{test:"Comprehensive Metabolic Panel",tube:"gold"}],expectedOrder:["gold","lavender"],safety:{question:"The patient says their veins roll. Which response best reflects safe beginner practice?",options:["Plan to redirect the needle several times if needed.","Assess the vein, anchor appropriately, choose equipment with the supervisor, and stop if the needle position is uncertain.","Skip palpation because the patient already knows their veins.","Use the deepest visible vein automatically."],correctIndex:1,explanation:"Patient history is useful, but the collector still assesses the site and uses controlled technique. Repeated probing is not the solution to a rolling vein."},explanation:"Gold/SST represents the serum hormone/chemistry testing in this training case; Lavender is used for the CBC."},
{id:"prep-follow-up",category:"PrEP Monitoring",title:"Routine Screening Labs",patient:{name:"Morgan Reed",dob:"01/15/1998",mrn:"TRAIN-004"},note:"I don't love needles, but I've never actually passed out.",orders:[{test:"HIV-1/2 Ag/Ab, 4th Generation",tube:"gold"},{test:"Syphilis screen with reflex",tube:"gold"},{test:"Comprehensive Metabolic Panel",tube:"gold"},{test:"Hepatitis C Antibody",tube:"gold"}],expectedOrder:["gold"],safety:{question:"The patient is nervous about needles. What is a helpful response?",options:["Tell them they need to watch the needle so they know what is happening.","Ask about prior reactions, position them safely, explain the plan calmly, and watch for symptoms of fainting.","Have them stand so they feel more in control.","Skip patient questions so the procedure is faster."],correctIndex:1,explanation:"Calm preparation, safe positioning, and assessment for prior reactions are appropriate. A patient should not be standing for venipuncture."},explanation:"These blood tests are represented by Gold/SST in this training scenario. In real collections, verify exact assay container and volume requirements."},
{id:"coag-butterfly",category:"Special Collection",title:"PT/INR With a Butterfly",patient:{name:"Cameron Brooks",dob:"09/09/1963",mrn:"TRAIN-005"},note:"Your supervisor has selected a winged (butterfly) collection device for this draw.",orders:[{test:"PT/INR",tube:"blue"},{test:"Comprehensive Metabolic Panel",tube:"gold"},{test:"CBC",tube:"lavender"}],expectedOrder:["blue","gold","lavender"],safety:{question:"The Light Blue tube is the first specimen and you are using a butterfly. What special step should you recognize?",options:["Shake the blue tube before inserting it into the holder.","Use a discard/lead tube first to clear the butterfly tubing dead space, following lab/device instructions.","Collect the Lavender tube first so the butterfly tubing fills with blood.","Only fill the Light Blue tube halfway."],correctIndex:1,explanation:"When a winged collection set is used and a citrate tube is first, Labcorp instructs use of a discard/lead tube to clear tubing dead space."},explanation:"Citrate (Light Blue) is collected before serum gel-barrier and EDTA tubes in this training draw. Correct fill of citrate tubes matters because the blood-to-anticoagulant ratio is important."},
{id:"fatigue-workup",category:"Safety Recognition",title:"Fatigue Workup",patient:{name:"Taylor Monroe",dob:"12/22/1975",mrn:"TRAIN-006"},note:"Everyone has a hard time getting my blood. During the attempt, I suddenly feel a sharp electrical pain shooting into my hand.",orders:[{test:"CBC with differential",tube:"lavender"},{test:"Comprehensive Metabolic Panel",tube:"gold"},{test:"Ferritin",tube:"gold"},{test:"Iron and TIBC",tube:"gold"},{test:"Vitamin B12",tube:"gold"},{test:"TSH",tube:"gold"}],expectedOrder:["gold","lavender"],safety:{question:"The patient reports sharp, electrical, radiating pain during needle insertion. What should the beginner do?",options:["Advance the needle slightly.","Redirect toward the vein while asking the patient to hold still.","Stop the draw, remove the needle safely, apply pressure, assess the patient, and notify the supervisor.","Finish the current tube before stopping."],correctIndex:2,explanation:"Sharp electrical or radiating pain is a stop signal. A beginner should not probe or continue an uncertain/unsafe attempt."},explanation:"This scenario tests whether safety overrides the goal of obtaining the specimen."},
{id:"order-of-draw",category:"Mixed Tube Draw",title:"Three-Tube Order of Draw",patient:{name:"Jamie Thompson",dob:"06/17/1982",mrn:"TRAIN-007"},note:"No special collection concerns are reported.",orders:[{test:"CBC",tube:"lavender"},{test:"CMP",tube:"gold"},{test:"PT/INR",tube:"blue"},{test:"Hemoglobin A1c",tube:"lavender"},{test:"Lipid Panel",tube:"gold"}],expectedOrder:["blue","gold","lavender"],safety:{question:"Which tube in this scenario deserves especially careful attention to proper fill?",options:["Gold/SST","Light Blue citrate","Lavender EDTA","They are all intentionally half-filled"],correctIndex:1,explanation:"Citrate coagulation tubes need the appropriate blood-to-anticoagulant ratio and should be filled according to the collection requirements."},explanation:"For this training set: Light Blue citrate comes before Gold/SST, and Lavender EDTA follows."},
{id:"labeling-safety",category:"Specimen Integrity",title:"Label Before You Leave",patient:{name:"Riley James",dob:"03/30/1990",mrn:"TRAIN-008"},note:"The draw is complete and the patient is still seated in front of you.",orders:[{test:"CBC",tube:"lavender"},{test:"CMP",tube:"gold"},{test:"Hemoglobin A1c",tube:"lavender"}],expectedOrder:["gold","lavender"],safety:{question:"What should happen before you leave the patient's side with the specimens?",options:["Set the unlabeled tubes on a shared counter and label them later.","Verify identifiers and label the specimens in the patient's presence according to clinic/lab procedure.","Ask another staff member to remember which tubes belong to the patient.","Put the tubes in your pocket until you reach the workstation."],correctIndex:1,explanation:"Specimens should be correctly identified and labeled in the patient's presence according to the applicable procedure."},explanation:"A technically successful draw is not complete until specimen identification and handling are correct."}
];

const state={mode:"beginner",scenarioOrder:[],index:0,score:0,correctDraws:0,safetyWins:0,selectedTubes:[],checked:false};
const $=s=>document.querySelector(s);
const els={startScreen:$("#startScreen"),gameScreen:$("#gameScreen"),resultsScreen:$("#resultsScreen"),modeLabel:$("#modeLabel"),roundLabel:$("#roundLabel"),scoreLabel:$("#scoreLabel"),progressBar:$("#progressBar"),scenarioCategory:$("#scenarioCategory"),scenarioTitle:$("#scenarioTitle"),patientName:$("#patientName"),patientDob:$("#patientDob"),patientMrn:$("#patientMrn"),patientNoteWrap:$("#patientNoteWrap"),patientNote:$("#patientNote"),ordersList:$("#ordersList"),hintLabel:$("#hintLabel"),tubeTray:$("#tubeTray"),selectedDraw:$("#selectedDraw"),safetySection:$("#safetySection"),safetyHeading:$("#safetyHeading"),safetyOptions:$("#safetyOptions"),checkButton:$("#checkButton"),resetDrawButton:$("#resetDrawButton"),restartButton:$("#restartButton"),feedback:$("#feedback"),correctStat:$("#correctStat"),safetyStat:$("#safetyStat"),bestScoreStat:$("#bestScoreStat"),cheatSheetButton:$("#cheatSheetButton"),cheatSheetDialog:$("#cheatSheetDialog"),resultsHeading:$("#resultsHeading"),finalScore:$("#finalScore"),resultsMessage:$("#resultsMessage"),resultsBreakdown:$("#resultsBreakdown"),playAgainButton:$("#playAgainButton"),resultsChangeModeButton:$("#resultsChangeModeButton")};

function shuffle(a){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function modeName(m){return({beginner:"Beginner",practice:"Practice",challenge:"Challenge"})[m]}
function scenario(){return state.scenarioOrder[state.index]}
function startGame(mode){Object.assign(state,{mode,scenarioOrder:shuffle(SCENARIOS),index:0,score:0,correctDraws:0,safetyWins:0,selectedTubes:[],checked:false});els.startScreen.classList.add("hidden");els.resultsScreen.classList.add("hidden");els.gameScreen.classList.remove("hidden");renderScenario()}

function renderScenario(){const s=scenario();state.selectedTubes=[];state.checked=false;els.modeLabel.textContent=modeName(state.mode);els.roundLabel.textContent=`Scenario ${state.index+1} of ${state.scenarioOrder.length}`;els.scoreLabel.textContent=`Score: ${state.score}`;els.progressBar.style.width=`${state.index/state.scenarioOrder.length*100}%`;els.scenarioCategory.textContent=s.category;els.scenarioTitle.textContent=s.title;els.patientName.textContent=s.patient.name;els.patientDob.textContent=s.patient.dob;els.patientMrn.textContent=s.patient.mrn;if(s.note){els.patientNote.textContent=`“${s.note}”`;els.patientNoteWrap.classList.remove("hidden")}else els.patientNoteWrap.classList.add("hidden");const hints=state.mode==="beginner";els.hintLabel.textContent=hints?"Tube hints are ON":"Tube hints are hidden";els.ordersList.innerHTML=s.orders.map(o=>{const t=TUBES[o.tube];return `<div class="order-item"><span class="order-name">${o.test}</span>${hints?`<span class="tube-hint"><span class="tube-dot tube-${t.css}"></span>${t.name}</span>`:""}</div>`}).join("");renderTubeTray();renderSelected();renderSafety(s);els.feedback.className="feedback hidden";els.feedback.innerHTML="";els.checkButton.disabled=false;els.resetDrawButton.disabled=false;updateStats()}

function renderTubeTray(){els.tubeTray.innerHTML=Object.entries(TUBES).map(([key,t])=>`<button class="tube-button ${state.selectedTubes.includes(key)?"selected":""}" data-tube="${key}" type="button" aria-pressed="${state.selectedTubes.includes(key)}"><span class="tube-illustration" aria-hidden="true"><span class="tube-cap cap-${t.css}"></span><span class="tube-body"></span></span><strong>${t.short}</strong><small>${t.additive}</small></button>`).join("")}
function renderSelected(){if(!state.selectedTubes.length){els.selectedDraw.className="selected-draw empty-state";els.selectedDraw.textContent="No tubes selected yet.";return}els.selectedDraw.className="selected-draw";els.selectedDraw.innerHTML=state.selectedTubes.map((k,i)=>{const t=TUBES[k];return `<span class="selected-chip"><span class="tube-dot tube-${t.css}"></span>${t.short}</span>${i<state.selectedTubes.length-1?'<span class="order-arrow">→</span>':""}`}).join("")}
function renderSafety(s){if(state.mode!=="challenge"||!s.safety){els.safetySection.classList.add("hidden");els.safetyOptions.innerHTML="";return}els.safetySection.classList.remove("hidden");els.safetyHeading.textContent=s.safety.question;els.safetyOptions.innerHTML=s.safety.options.map((o,i)=>`<label class="choice-option"><input type="radio" name="safetyAnswer" value="${i}"><span>${o}</span></label>`).join("")}
function equal(a,b){return a.length===b.length&&a.every((v,i)=>v===b[i])}
function sameSet(a,b){return a.length===b.length&&a.every(v=>b.includes(v))}
function formatOrder(keys){return keys.map(k=>TUBES[k].short).join(" → ")}

function checkAnswer(){if(state.checked)return;const s=scenario();if(!state.selectedTubes.length)return temp("Choose at least one tube before checking your draw.");const exact=equal(state.selectedTubes,s.expectedOrder);const types=sameSet(state.selectedTubes,s.expectedOrder);let safety=null;if(state.mode==="challenge"&&s.safety){const picked=$("input[name='safetyAnswer']:checked");if(!picked)return temp("Choose a safety answer before checking this Challenge scenario.");safety=Number(picked.value)===s.safety.correctIndex}state.checked=true;let earned=0;if(exact){earned+=10;state.correctDraws++}else if(types)earned+=5;if(safety===true){earned+=5;state.safetyWins++}state.score+=earned;els.scoreLabel.textContent=`Score: ${state.score}`;updateStats();const parts=[];if(exact)parts.push("✅ Correct tube types and order of draw.");else if(types)parts.push(`🟡 You chose the right tube types, but the order should be: ${formatOrder(s.expectedOrder)}.`);else parts.push(`🟡 Review the tube selection. For this training scenario, the expected draw is: ${formatOrder(s.expectedOrder)}.`);if(safety===true)parts.push(`✅ Safety decision: correct. ${s.safety.explanation}`);if(safety===false)parts.push(`🟡 Safety decision: review this one. ${s.safety.explanation}`);parts.push(s.explanation);parts.push("For real patient collection, verify the exact test/container requirements in the current laboratory directory and follow clinic policy/supervisor direction.");const perfect=exact&&(safety===null||safety===true);els.feedback.className=`feedback ${perfect?"correct":"partial"}`;els.feedback.innerHTML=`<strong>${perfect?"Great draw!":"Good practice — review the feedback."} +${earned} points</strong><ul>${parts.map(p=>`<li>${p}</li>`).join("")}</ul><button id="nextButton" class="button button-primary next-button" type="button">${state.index===state.scenarioOrder.length-1?"See Results":"Next Scenario"}</button>`;els.feedback.classList.remove("hidden");els.feedback.focus();els.checkButton.disabled=true;els.resetDrawButton.disabled=true;$("#nextButton").addEventListener("click",nextScenario)}
function temp(msg){els.feedback.className="feedback partial";els.feedback.innerHTML=`<strong>Almost ready.</strong>${msg}`;els.feedback.classList.remove("hidden");els.feedback.focus()}
function nextScenario(){if(state.index>=state.scenarioOrder.length-1)return showResults();state.index++;renderScenario();window.scrollTo({top:0,behavior:"smooth"})}
function maxScore(){return SCENARIOS.length*10+(state.mode==="challenge"?SCENARIOS.filter(s=>s.safety).length*5:0)}
function showResults(){const max=maxScore(),pct=Math.round(state.score/max*100);els.gameScreen.classList.add("hidden");els.resultsScreen.classList.remove("hidden");els.finalScore.textContent=state.score;els.resultsHeading.textContent=pct>=90?"Excellent session.":pct>=70?"Strong practice round.":"Good start — keep building the pattern.";els.resultsMessage.textContent=pct>=90?"You consistently matched the training tubes and sequence. Keep verifying real-world orders instead of relying on memory alone.":"Replay the scenarios and pay attention to the feedback. The goal is a safe, repeatable routine — not speed.";els.resultsBreakdown.innerHTML=`<div class="result-stat"><strong>${state.correctDraws}/${SCENARIOS.length}</strong><span>Perfect draws</span></div><div class="result-stat"><strong>${state.mode==="challenge"?state.safetyWins:"—"}</strong><span>Safety wins</span></div><div class="result-stat"><strong>${pct}%</strong><span>Session score</span></div>`;const best=Math.max(state.score,Number(localStorage.getItem("phlebBestScore")||0));localStorage.setItem("phlebBestScore",String(best));updateStats();window.scrollTo({top:0,behavior:"smooth"})}
function updateStats(){els.correctStat.textContent=state.correctDraws;els.safetyStat.textContent=state.safetyWins;els.bestScoreStat.textContent=localStorage.getItem("phlebBestScore")||"0"}
function resetToStart(){els.gameScreen.classList.add("hidden");els.resultsScreen.classList.add("hidden");els.startScreen.classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}

document.querySelectorAll(".mode-card").forEach(b=>b.addEventListener("click",()=>startGame(b.dataset.mode)));
els.tubeTray.addEventListener("click",e=>{const b=e.target.closest(".tube-button");if(!b||state.checked)return;const k=b.dataset.tube,i=state.selectedTubes.indexOf(k);if(i>=0)state.selectedTubes.splice(i,1);else state.selectedTubes.push(k);renderTubeTray();renderSelected()});
els.checkButton.addEventListener("click",checkAnswer);
els.resetDrawButton.addEventListener("click",()=>{if(state.checked)return;state.selectedTubes=[];renderTubeTray();renderSelected();els.feedback.classList.add("hidden")});
els.restartButton.addEventListener("click",resetToStart);els.resultsChangeModeButton.addEventListener("click",resetToStart);els.playAgainButton.addEventListener("click",()=>startGame(state.mode));els.cheatSheetButton.addEventListener("click",()=>els.cheatSheetDialog.showModal());updateStats();
